import matplotlib.pyplot as plt
import numpy as np

# Function to plot the route
def plot_route(route, distance_matrix):
    num_places = len(distance_matrix)
    places = np.arange(num_places)
    plt.figure(figsize=(8, 6))
    plt.plot(places[route], places[route], 'r.-')
    plt.xticks(places)
    plt.yticks(places)
    plt.xlabel('Places')
    plt.ylabel('Places')
    plt.title('Route Generated by Hill Climbing Algorithm')
    plt.grid(True)
    plt.show()
